name: docker_build_push_acr

on:
  workflow_dispatch:

jobs:
  docker_build_push_acr:
    name: 'Docker Build and Push to ACR'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    env:
      DIRECTORY_NAME: DienstDuizend.BusinessCatalogueService
      IMAGE_NAME: business-catalogue-service

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x' # Specify the .NET version you need

    - name: Restore dependencies
      run: dotnet restore ${{ env.DIRECTORY_NAME }}

    - name: Build
      run: dotnet build ${{ env.DIRECTORY_NAME }} --configuration Release --no-restore

    - name: Run tests
      run: dotnet test tests/${{ env.DIRECTORY_NAME }}.IntegrationTests --configuration Release --no-restore --no-build

    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build the frontend image and push it to ACR
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
        file: src/${{ env.DIRECTORY_NAME }}/Dockerfile
